# --- project-relative paths (generalized from the scratch build workspace) ---
# Set TDD_BASE to the project root, or leave blank to auto-detect (parent of scripts/).
import os
TDD_BASE = os.environ.get("TDD_BASE") or os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA_DIR    = os.path.join(TDD_BASE, "data")
DASH_DIR    = os.path.join(TDD_BASE, "dashboard")
DOCS_DIR    = os.path.join(TDD_BASE, "docs")
PORT_DIR    = os.path.join(TDD_BASE, "portfolio")
SCRIPTS_DIR = os.path.join(TDD_BASE, "scripts")
# ---------------------------------------------------------------------------

import os
from graphviz import Digraph
OUT=os.path.join(DOCS_DIR,'diagrams')
os.makedirs(OUT,exist_ok=True)

GOLD="#E0A106"; DGOLD="#B07D04"; INK="#1F2937"; BLUE="#2E75B6"; GRAY="#6B7280"
RED="#C0392B"; GREEN="#2E7D32"
SRC_F="#FFF7E6"; PIPE_F="#EAF2FB"; RT_F="#F3F4F6"; CONN_F="#FDECEA"; AUTO_F="#E8F5E9"
FONT="Helvetica"

def base(name,rankdir="TB"):
    g=Digraph(name)
    g.attr(rankdir=rankdir,bgcolor="white",fontname=FONT)
    g.attr('graph',dpi="150",pad="0.3",nodesep="0.35",ranksep="0.55",fontname=FONT)
    g.attr('node',fontname=FONT,fontsize="11",style="filled,rounded",shape="box",
           color=INK,fillcolor="white",penwidth="1.2",margin="0.14,0.08")
    g.attr('edge',fontname=FONT,fontsize="9.5",color=GRAY,penwidth="1.1")
    return g

# ---------- 1. SYSTEM ARCHITECTURE ----------
g=base("arch_system")
g.attr(label="Tech Drawdown — System Architecture",labelloc="t",fontsize="16",fontcolor=INK)
with g.subgraph(name="cluster_src") as c:
    c.attr(label="1 · Data Sources (local, private)",style="filled,rounded",fillcolor=SRC_F,color=GOLD,fontcolor=DGOLD,fontsize="12")
    c.node("uwb","Universe Workbook\ntech100_drawdown_SP_NAS.xlsx\nmembership + static cols + STOCKHISTORY fallback",fillcolor="white",color=GOLD)
    c.node("ira_src","IRA.xlsx\n(holdings export)",fillcolor="white",color=GOLD)
    c.node("bk_src","Brokerage.xlsx\n(holdings export)",fillcolor="white",color=GOLD)
    c.node("pwb","IRA_Portfolio.xlsx /\nBrokerage_Portfolio.xlsx\n(live-formula workbooks)",fillcolor="white",color=GOLD,fontcolor=GRAY)
with g.subgraph(name="cluster_pipe") as c:
    c.attr(label="2 · Build & Publish Pipeline (Python)",style="filled,rounded",fillcolor=PIPE_F,color=BLUE,fontcolor=BLUE,fontsize="12")
    c.node("build","build_market_data.py\nFMP -> STOCKHISTORY tail -> carry-forward",fillcolor="white",color=BLUE)
    c.node("guard","integrity_guard.py\n52-wk band / ratio · dq flag",fillcolor="white",color=BLUE)
    c.node("mdx","market_data.xlsx\n(FMP-written live data)",shape="cylinder",fillcolor="white",color=BLUE)
    c.node("json","DATA · 19 keys\nuniverse + holdings + coreRank + splits +\nindexHistory + macroHistory + history + alerts +\ndividends + dcf + lookthrough + earnings + dcfMonitor",shape="cylinder",fillcolor="white",color=BLUE)
    c.node("tpl","dashboard_tpl.html\nconst DATA = __DATA__",fillcolor="white",color=BLUE)
    c.node("dep","tech_drawdown_dashboard.html\n(deployed, DATA injected)",fillcolor="white",color=BLUE)
with g.subgraph(name="cluster_rt") as c:
    c.attr(label="3 · Dashboard Runtime (browser)",style="filled,rounded",fillcolor=RT_F,color=GRAY,fontcolor=INK,fontsize="12")
    c.node("art","Deployed HTML\ntech_drawdown_dashboard.html",fillcolor="white",color=INK)
    c.node("tabs","9 tabs: universe (6) +\nIRA / Brokerage / Retirement",fillcolor="white",color=GRAY)
    c.node("popup","Fundamentals popup\nrisk · advisor scorecard",fillcolor="white",color=GRAY)
    c.node("cache","localStorage cache\ntdd_pcache_v5 (TTL-tiered)",shape="cylinder",fillcolor="white",color=GRAY)
    c.node("rank","Rules ranking engine\nsector · fund · growth-core\n(weights · thresholds · IF/THEN)",fillcolor="white",color=GRAY)
    c.node("bdx","BDX provider adapter\nconnector I/O + shape mapping",fillcolor="white",color=GRAY)
with g.subgraph(name="cluster_conn") as c:
    c.attr(label="4a · Live Data Connectors",style="filled,rounded",fillcolor=CONN_F,color=RED,fontcolor=RED,fontsize="12")
    c.node("fmp","FMP MCP\nbatch-quote · universe live data",fillcolor="white",color=RED)
    c.node("bd","Bigdata MCP\nfind_securities · tearsheets\n(holdings · off-index · fundamentals)",fillcolor="white",color=RED)
with g.subgraph(name="cluster_auto") as c:
    c.attr(label="4b · Automation",style="filled,rounded",fillcolor=AUTO_F,color=GREEN,fontcolor=GREEN,fontsize="12")
    c.node("cron","Local daily refresh · 9am\nfetch FMP -> build -> guard -> import ->\nreprice -> regenerate -> write HTML",fillcolor="white",color=GREEN)
g.edge("fmp","build",label="live universe",color=RED)
g.edge("uwb","build",label="membership + static + fallback"); g.edge("ira_src","build"); g.edge("bk_src","build")
g.edge("ira_src","pwb",style="dashed",color=GRAY,label="Excel build"); g.edge("bk_src","pwb",style="dashed",color=GRAY)
g.edge("build","mdx"); g.edge("build","guard"); g.edge("guard","json"); g.edge("json","dep"); g.edge("tpl","dep",label="inject")
g.edge("dep","art",label="open locally")
g.edge("art","tabs"); g.edge("art","popup"); g.edge("tabs","cache",dir="both",style="dashed")
g.edge("tabs","bdx",label="live prices"); g.edge("popup","bdx",label="fundamentals"); g.edge("popup","rank",style="dashed",label="rankings")
g.edge("bdx","bd",label="holdings connector calls",color=RED)
g.edge("cron","fmp",color=GREEN,label="fetch universe"); g.edge("cron","uwb",style="dashed",color=GREEN,label="static+fallback"); g.edge("cron","ira_src",style="dashed",color=GREEN)
g.edge("cron","bd",color=GREEN,label="off-index reprice"); g.edge("cron","dep",color=GREEN,label="regenerate"); g.edge("cron","art",color=GREEN,label="write HTML")
g.render(os.path.join(OUT,"01_architecture"),format="png",cleanup=False)

# ---------- 2. DATA FLOW ----------
g=base("dataflow",rankdir="LR")
g.attr(label="Data-Flow Diagram",labelloc="t",fontsize="15",fontcolor=INK)
g.node("fmp","FMP connector\nbatch-quote: price/high/low/50-200 SMA",fillcolor=CONN_F,color=RED,shape="component")
g.node("s1","Universe workbook\nmembership + static + STOCKHISTORY fallback",fillcolor=SRC_F,color=GOLD,shape="folder")
g.node("s2","IRA.xlsx /\nBrokerage.xlsx",fillcolor=SRC_F,color=GOLD,shape="folder")
g.node("p1","build_market_data.py\nprovider chain + integrity guard",fillcolor=PIPE_F,color=BLUE)
g.node("mdx","market_data.xlsx\n(machine-written)",fillcolor=PIPE_F,color=BLUE,shape="cylinder")
g.node("j","DATA · 19 keys\nuniverse(6) + ira·brokerage·coreRank·splits·\nindexHistory·macroHistory·history·alerts·dividends·\ndcf·lookthrough·earnings·dcfMonitor",fillcolor=PIPE_F,color=BLUE,shape="cylinder")
g.node("t","dashboard_tpl.html",fillcolor=PIPE_F,color=BLUE)
g.node("d","deployed HTML\n(DATA embedded)",fillcolor=PIPE_F,color=BLUE)
g.node("a","Deployed HTML",fillcolor=RT_F,color=INK)
g.node("c","Bigdata connector",fillcolor=CONN_F,color=RED)
g.edge("fmp","p1",label="universe live",color=RED,style="bold")
g.edge("s1","p1",label="membership/static + fallback"); g.edge("s2","p1",label="holdings")
g.edge("p1","mdx"); g.edge("p1","j"); g.edge("j","d",label="inject into"); g.edge("t","d")
g.edge("d","a",label="write files")
g.edge("c","a",label="live prices &\nfundamentals\n(runtime)",color=RED,style="bold")
g.render(os.path.join(OUT,"02_dataflow"),format="png",cleanup=False)

# ---------- 3. BUILD & PUBLISH PROCESS ----------
g=base("build_process")
g.attr(label="Build & Publish Process",labelloc="t",fontsize="15",fontcolor=INK)
g.node("a0","Fetch FMP batch-quote\n(universe, <=450/chunk; [] on fail)",fillcolor=CONN_F,color=RED)
g.node("a1","build_market_data.py:\nFMP -> STOCKHISTORY tail -> carry-forward",fillcolor=PIPE_F,color=BLUE)
g.node("a2","integrity_guard:\n52-wk band / ratio · suppress + dq",fillcolor="#FFF7E6",color=GOLD,shape="diamond")
g.node("a3","Preserve / import\nira · brokerage · coreRank · splits",fillcolor=PIPE_F,color=BLUE)
g.node("ahist","build_index_history.py + build_macro_history.py\nindex + macro/commodities 1-yr weekly ·\npreserve + carry-forward on gate/fail",fillcolor=PIPE_F,color=BLUE)
g.node("aderiv","7 pure transforms (no connector calls, preserve-on-fail)\nbuild_history.py -> benchmark/timeline · build_alerts.py -> alerts (dq-guarded)\nbuild_dividends.py -> 12-mo calendar · build_dcf.py -> valuation bases\nbuild_lookthrough.py -> fund look-through\nbuild_earnings.py -> earnings memos · dcf_monitor.js -> valuation drift",fillcolor=PIPE_F,color=BLUE)
g.node("a4","Assemble DATA (19 keys)\n+ write market_data.xlsx",fillcolor=PIPE_F,color=BLUE,shape="cylinder")
g.node("aM","assemble_dashboard.py\n(src/dash 27 modules -> template ·\nbyte-for-byte golden-master)",fillcolor=PIPE_F,color=BLUE)
g.node("a5","Inject into template\n(replace __DATA__)",fillcolor=PIPE_F,color=BLUE)
g.node("a6","Validate:\nnode parse · </html> ·\ntwo </script>",fillcolor="#FFF7E6",color=GOLD,shape="diamond")
g.node("a7","Write deployed HTML",fillcolor=PIPE_F,color=BLUE)
g.node("a8","Write both HTML copies",fillcolor=RT_F,color=INK)
for a,b in [("a0","a1"),("a1","a2"),("a2","a3"),("a3","ahist"),("ahist","aderiv"),("aderiv","a4"),("a4","aM"),("aM","a5"),("a5","a6")]: g.edge(a,b)
g.edge("a6","a7",label="pass"); g.edge("a6","a1",label="fail -> fix",color=RED,style="dashed")
g.edge("a7","a8")
g.render(os.path.join(OUT,"03_build_process"),format="png",cleanup=False)

# ---------- 4. SCHEDULED REFRESH WORKFLOW ----------
g=base("wf_scheduled")
g.attr(label="Daily Scheduled Refresh — Workflow",labelloc="t",fontsize="15",fontcolor=INK)
g.node("start","Trigger 9am",shape="oval",fillcolor=AUTO_F,color=GREEN)
g.node("g0","Main workbook\nintact? (zip·EOCD·6 sheets)",shape="diamond",fillcolor="#FFF7E6",color=GOLD)
g.node("abort","ABORT — keep last good\nreport failed check",fillcolor="#FDECEA",color=RED,shape="box")
g.node("read","Fetch FMP + build universe\n(chain; STOCKHISTORY fallback if FMP down)",fillcolor=PIPE_F,color=BLUE)
g.node("guard","Integrity guard\nsuppress corrupt/#N/A · dq flag",fillcolor="#FFF7E6",color=GOLD)
g.node("keep","Load existing DATA\n(fallback for ira/brokerage/coreRank)",fillcolor=PIPE_F,color=BLUE)
g.node("g1","IRA.xlsx / Brokerage.xlsx\nreadable? (gate)",shape="diamond",fillcolor="#FFF7E6",color=GOLD)
g.node("imp","RE-IMPORT holdings\n(carry prior live fields)",fillcolor=PIPE_F,color=BLUE)
g.node("skip","SKIP → preserve prior\n⚠ flag in report",fillcolor="#FFF3CD",color=DGOLD)
g.node("off","Derive off-index set\n(marketable ∉ universe)",fillcolor=PIPE_F,color=BLUE)
g.node("reprice","Reprice off-index via connector\n(resolve → tearsheet → recompute)",fillcolor=CONN_F,color=RED)
g.node("g2","fetch ok?",shape="diamond",fillcolor="#FFF7E6",color=GOLD)
g.node("keepold","Keep prior/last-known price\n(never blank)",fillcolor="#FFF3CD",color=DGOLD)
g.node("rcore","Recompute growth-core\n(recompute_core.js;\npreserve prior on fail)",fillcolor=PIPE_F,color=BLUE)
g.node("hist","Refresh index + macro history\n(FMP chart/commodity/forex/economics;\npreserve prior · carry-forward on gate/fail)",fillcolor=PIPE_F,color=BLUE)
g.node("deriv","Derived feeds (pure transforms)\nhistory · alerts · dividends ·\nDCF bases (~6 new syms/run) ·\nlook-through (~4 new funds/run)\npreserve prior on any failure",fillcolor=PIPE_F,color=BLUE)
g.node("regen","Regenerate + validate HTML",fillcolor=PIPE_F,color=BLUE)
g.node("pub","Write both HTML copies",fillcolor=RT_F,color=INK)
g.node("rep","Report: sync status · UNIVERSE SOURCE\n(FMP / STOCKHISTORY-tail / carry-fwd) ·\ndata-integrity · off-index prices ·\nalerts · dividends · DCF · look-through coverage",shape="oval",fillcolor=AUTO_F,color=GREEN)
g.node("log","Persist run log\n(log_util.py -> logs\\: run_*.jsonl +\nlatest_run.md + runs.jsonl history)",fillcolor=PIPE_F,color=BLUE)
g.edge("start","g0")
g.edge("g0","abort",label="no",color=RED); g.edge("g0","read",label="yes")
g.edge("read","keep"); g.edge("keep","g1")
g.edge("g1","imp",label="yes"); g.edge("g1","skip",label="no")
g.edge("imp","off"); g.edge("skip","off")
g.edge("off","reprice"); g.edge("reprice","g2")
g.edge("g2","rcore",label="yes"); g.edge("g2","keepold",label="no"); g.edge("keepold","rcore"); g.edge("rcore","guard"); g.edge("guard","hist"); g.edge("hist","deriv"); g.edge("deriv","regen")
g.edge("regen","pub"); g.edge("pub","rep"); g.edge("rep","log")
g.render(os.path.join(OUT,"04_scheduled_workflow"),format="png",cleanup=False)

# ---------- 5. LIVE-PRICE RUNTIME WORKFLOW ----------
g=base("wf_liveprice")
g.attr(label="Runtime — Load Live Prices Workflow (IRA / Brokerage tab)",labelloc="t",fontsize="14",fontcolor=INK)
g.node("t1","Open tab (auto, 1×/day)\nor click ↻ Load live prices",shape="oval",fillcolor=RT_F,color=INK)
g.node("t2","connector reachable?",shape="diamond",fillcolor="#FFF7E6",color=GOLD)
g.node("t2b","Use import / universe value\n(hide button)",fillcolor="#FFF3CD",color=DGOLD)
g.node("t3","For each marketable holding\n(pool ≈4)",fillcolor=PIPE_F,color=BLUE)
g.node("t4","livePrice(ticker)\nLP: cache (DAY TTL)?",shape="diamond",fillcolor="#FFF7E6",color=GOLD)
g.node("t5","resolveTyped → find_securities\n(exact :TICKER listing)",fillcolor=CONN_F,color=RED)
g.node("t6","company_tearsheet /\netf_tearsheet",fillcolor=CONN_F,color=RED)
g.node("t7","parse price · high · MAs →\nLIVEPX[ticker]",fillcolor=PIPE_F,color=BLUE)
g.node("t8","Market Value = qty × live price\nrecompute G/L · weight · KPIs",fillcolor=PIPE_F,color=BLUE)
g.node("t9","Re-render panel + 'as of' stamp",shape="oval",fillcolor=RT_F,color=INK)
g.edge("t1","t2"); g.edge("t2","t2b",label="no",color=RED); g.edge("t2","t3",label="yes")
g.edge("t3","t4"); g.edge("t4","t8",label="hit",color=GREEN); g.edge("t4","t5",label="miss")
g.edge("t5","t6"); g.edge("t6","t7"); g.edge("t7","t8"); g.edge("t8","t9")
g.render(os.path.join(OUT,"05_liveprice_workflow"),format="png",cleanup=False)

# ---------- 6. HOLDINGS UPDATE WORKFLOW ----------
g=base("wf_holdings",rankdir="LR")
g.attr(label="Holdings-Update Workflow (hands-off after edit)",labelloc="t",fontsize="14",fontcolor=INK)
g.node("h1","You edit a row in\nIRA.xlsx / Brokerage.xlsx",fillcolor=SRC_F,color=GOLD,shape="note")
g.node("h2","OneDrive syncs\n(hydrated on device)",fillcolor=RT_F,color=GRAY)
g.node("h3","Next 9am task:\nre-import holdings",fillcolor=AUTO_F,color=GREEN)
g.node("h4","New off-index name?\nauto-detected",shape="diamond",fillcolor="#FFF7E6",color=GOLD)
g.node("h5","Reprice via connector",fillcolor=CONN_F,color=RED)
g.node("h6","In-universe → prices\nfrom universe tab",fillcolor=PIPE_F,color=BLUE)
g.node("h7","Regenerate + write HTML →\nappears in dashboard",fillcolor=RT_F,color=INK,shape="oval")
g.edge("h1","h2"); g.edge("h2","h3"); g.edge("h3","h4")
g.edge("h4","h5",label="yes"); g.edge("h4","h6",label="no"); g.edge("h5","h7"); g.edge("h6","h7")
g.render(os.path.join(OUT,"06_holdings_workflow"),format="png",cleanup=False)

# ---------- 7. LIVE-PRICE SEQUENCE (linear) ----------
g=base("seq_liveprice",rankdir="LR")
g.attr(label="Sequence — Live Price Fetch",labelloc="t",fontsize="14",fontcolor=INK)
g.attr('node',shape="box")
g.node("u","User / auto-open",fillcolor=RT_F,color=INK)
g.node("panel","Portfolio panel",fillcolor=PIPE_F,color=BLUE)
g.node("lp","livePrice()",fillcolor=PIPE_F,color=BLUE)
g.node("ca","localStorage LP:",fillcolor=RT_F,color=GRAY,shape="cylinder")
g.node("rt","resolveTyped()",fillcolor=PIPE_F,color=BLUE)
g.node("bd","Bigdata MCP",fillcolor=CONN_F,color=RED)
g.edge("u","panel",label="1 trigger")
g.edge("panel","lp",label="2 per holding")
g.edge("lp","ca",label="3 check TTL",dir="both")
g.edge("lp","rt",label="4 on miss")
g.edge("rt","bd",label="5 find_securities")
g.edge("bd","rt",label="6 id + type",style="dashed")
g.edge("rt","bd",label="7 tearsheet")
g.edge("bd","lp",label="8 price/high/MAs",style="dashed")
g.edge("lp","panel",label="9 LIVEPX → recompute",style="dashed")
g.render(os.path.join(OUT,"07_sequence"),format="png",cleanup=False)


# ---------- 8. RULES-BASED RANKING ENGINE ----------
g=base("ranking_engine")
g.attr(label="Rules-Based Ranking Engine (V2)",labelloc="t",fontsize="15",fontcolor=INK)
with g.subgraph(name="cluster_src2") as c:
    c.attr(label="Source of truth · src/ranking",style="filled,rounded",fillcolor=SRC_F,color=GOLD,fontcolor=DGOLD,fontsize="12")
    c.node("eng","engine.js\nscoreItem · rankGroup ·\nconditions · validateRuleset",fillcolor="white",color=GOLD)
    c.node("store","store.js\nactive · presets · export/import",fillcolor="white",color=GOLD)
    c.node("rs","rulesets/*.json\ncompany_fundamentals · sector_company\nfund_category · growth_core",fillcolor="white",color=GOLD,shape="note")
with g.subgraph(name="cluster_inj") as c:
    c.attr(label="Injection (single source)",style="filled,rounded",fillcolor=PIPE_F,color=BLUE,fontcolor=BLUE,fontsize="12")
    c.node("sync","sync_engine.js\n-> inline block in template",fillcolor="white",color=BLUE)
with g.subgraph(name="cluster_use") as c:
    c.attr(label="In the artifact",style="filled,rounded",fillcolor=RT_F,color=GRAY,fontcolor=INK,fontsize="12")
    c.node("r3","3 rankings\nsector · fund · growth-core",fillcolor="white",color=INK)
    c.node("ed","Editor UI\nweight sliders · thresholds ·\nconditions builder",fillcolor="white",color=GRAY)
    c.node("xp","Explain-per-row\nscore breakdown + fired rules",fillcolor="white",color=GRAY)
g.node("day","Daily task\nrecompute_core.js -> coreRank",fillcolor=AUTO_F,color=GREEN)
g.edge("eng","sync"); g.edge("store","sync"); g.edge("rs","sync")
g.edge("sync","r3",label="inlined"); g.edge("ed","r3",dir="both",label="live re-rank"); g.edge("r3","xp")
g.edge("rs","day",style="dashed",color=GREEN,label="growth_core"); g.edge("eng","day",style="dashed",color=GREEN)
g.render(os.path.join(OUT,"08_ranking_engine"),format="png",cleanup=False)

# ---------- 9. UNIVERSE DATA SOURCING — PROVIDER CHAIN ----------
g=base("data_sourcing",rankdir="LR")
g.attr(label="Universe Data Sourcing — Provider Chain (per ticker)",labelloc="t",fontsize="14",fontcolor=INK)
g.node("tk","Universe ticker",shape="oval",fillcolor=RT_F,color=INK)
g.node("q1","FMP batch-quote\nreturns a price?",shape="diamond",fillcolor="#FFF7E6",color=GOLD)
g.node("fmp","FMP row\nprice · 52wk high/low · 50/200 SMA",fillcolor=CONN_F,color=RED)
g.node("q2","STOCKHISTORY value\npasses guard?",shape="diamond",fillcolor="#FFF7E6",color=GOLD)
g.node("sh","STOCKHISTORY tail rung\n(workbook, guard-validated)",fillcolor=SRC_F,color=GOLD)
g.node("q3","prior market_data.xlsx\nhas a value?",shape="diamond",fillcolor="#FFF7E6",color=GOLD)
g.node("cf","Carry-forward\n(dq: stale)",fillcolor="#FFF3CD",color=DGOLD)
g.node("miss","Missing\n(dq flag / badge)",fillcolor=CONN_F,color=RED)
g.node("guard","integrity_guard\n52-wk band / ratio",fillcolor="#FFF7E6",color=GOLD)
g.node("data","DATA universe row",shape="oval",fillcolor=RT_F,color=INK)
g.edge("tk","q1")
g.edge("q1","fmp",label="yes (~99%)",color=GREEN); g.edge("q1","q2",label="no")
g.edge("q2","sh",label="yes (~11 funds)"); g.edge("q2","q3",label="no")
g.edge("q3","cf",label="yes"); g.edge("q3","miss",label="no",color=RED)
g.edge("fmp","guard"); g.edge("sh","guard"); g.edge("cf","guard")
g.edge("guard","data"); g.edge("miss","data",style="dashed")
g.render(os.path.join(OUT,"09_data_sourcing"),format="png",cleanup=False)

print("diagrams:")
for f in sorted(os.listdir(OUT)): print("  ",f, os.path.getsize(os.path.join(OUT,f)))
