"""Assemble dashboard_tpl.html from ordered source modules in src/dash/.
Build-time concatenation (the deployed artifact must stay ONE self-contained file —
no runtime ES modules over file://). The MANIFEST order is load order: head/style/body,
then the DATA placeholder, then JS modules (helpers before the load-time IIFEs that use
them), then the closing tail. Golden-master: the assembled output must equal the current
dashboard_tpl.html byte-for-byte until the modules are trusted as the source of truth.
Usage: python assemble_dashboard.py            # verify assembled == dashboard_tpl.html
       python assemble_dashboard.py --write     # (re)write dashboard_tpl.html from modules
"""
import os, sys, hashlib
HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(os.path.dirname(HERE), 'src', 'dash')  # project-root src/dash (beside src/ranking)
TPL  = os.path.join(HERE, 'dashboard_tpl.html')

# Ordered manifest = original document order = JS load order.
MANIFEST = [
    '00_head.html',        # <head> + <style> + nav + empty panels + <script> open
    '01_data.js',          # const DATA = __DATA__;
    '05_debug.js',        # DBG logger + opt-in debug panel (?debug=1 / Shift+D)
    '12_glossary_data.js', # GENERATED glossary (build_glossary.py) — BEFORE 10_helpers (which eagerly builds panels at load)
    '12_glossary.js',      # hcol()/decorateHeaders() + column tooltip — must define GLOSS before makeTable runs
    '10_helpers.js',       # colors, Chart plugins, cell/chip helpers, makeTable, buildStockPanel
    '20_universe.js',      # tab maps, uniqUniverse, tabChips
    '30_overview.js',      # Overview spectrum boards + KPIs (load-time IIFE)
    '40_charts.js',        # buildIndexChart + buildMacro (load-time IIFEs)
    '45_benchmark.js',     # buildBenchmark — portfolio vs Dow/Nasdaq/S&P (called by buildRetirePanel; define BEFORE 60_portfolio)
    '46_drawdown.js',      # buildDrawdown — underwater drawdown timeline (called by buildRetirePanel; define BEFORE 60_portfolio)
    '49_montecarlo.js',    # MC engine + openMonteCarlo popup; mcMedian() feeds the KPI tile (define BEFORE 60_portfolio)
    '52_lookthrough.js',   # fund look-through roll-up + openLookthrough popup; ltTopHidden() feeds the KPI tile (BEFORE 60_portfolio)
    '50_fundpanel.js',     # etfLiveMetrics + buildFundPanel
    '60_portfolio.js',     # LIVEPX, mktValue, IRA/Brokerage/retire
    '70_connector.js',     # BDX prefix, caches, resolveEntity
    '72_liveprice.js',     # live-price service (livePrice, attachLivePrices, runLive)
    '74_fundamentals.js',  # esg/kfh, mcpCall, BDX adapter object, openTicker popup
    '48_alerts.js',       # openAlert popup + .alertb click delegation (uses ov/mTitle/mBody from 74)
    '47_dividends.js',    # openDividends popup + .kpidiv click (uses ov/mTitle/mBody from 74 + Chart)
    '51_dcf.js',          # DCF: fetch base once (BDX.dcfRaw) + local model, fair-value strip + openDCF popup
    '53_earnings.js',     # earnings memo badge (earnMemoBadge, hoisted -> tkrCell) + openEarnings popup
    '76_ranking_engine.js',# ranking block //__RANKING_BEGIN__..//__RANKING_END__ (generated by sync_engine.js)
    '78_ranking_ui.js',    # ranking rulesets, editor, conditions, explain popover
    '80_rankings_open.js', # openSectorRanking / openCategoryRanking
    '90_init.js',          # risk summary, tab wiring, boot
    '99_tail.html',        # </script></body></html>
]

def assemble():
    parts = []
    for name in MANIFEST:
        with open(os.path.join(SRC, name), 'rb') as fh:
            parts.append(fh.read())
    return b''.join(parts)

def write():
    built = assemble()
    with open(TPL, 'wb') as fh:
        fh.write(built)
    return built

def main():
    built = assemble()
    if '--write' in sys.argv:
        write()
        print('wrote', os.path.relpath(TPL), len(built), 'bytes')
        return
    cur = open(TPL, 'rb').read()
    same = built == cur
    print('assembled', len(built), 'bytes  sha', hashlib.sha256(built).hexdigest()[:12])
    print('current  ', len(cur), 'bytes  sha', hashlib.sha256(cur).hexdigest()[:12])
    print('GOLDEN-MASTER MATCH:', same)
    if not same:
        n = min(len(built), len(cur))
        i = next((k for k in range(n) if built[k] != cur[k]), n)
        print('first diff at byte', i, '| lens', len(built), len(cur))
        sys.exit(1)

if __name__ == '__main__':
    main()
